#!/bin/bash
source "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"/include/env

source ${SCRIPT_DIR}/loader/bin/activate

function load()
{
    if [ ! -f "${INCLUDE_DIR}/appinfo" ];then
        echo "appinfo file is missing, build ledger app first"
        exit 0
    else
        source ${INCLUDE_DIR}/appinfo
    fi

    python3 -m ledgerblue.loadApp --targetId ${DEVICE_ID} --fileName ${ROOT_DIR}/bin/app.hex \
    --appName ${APP_NAME} --appVersion ${APP_VER} --dataSize ${APP_SIZE} --icon ${ICON_HEX} \
    --appFlags 0x40 --path "44'/14336'" --curve secp256k1 --tlv --apdu

    exit 0
}

function unload()
{ 
    python3 -m ledgerblue.deleteApp --targetId ${DEVICE_ID} --appName ${APP_NAME}
    exit 0
}

$1

load