#!/bin/bash
source "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"/include/env
source ${SCRIPT_DIR}/loader/bin/activate

if [ -f "${INCLUDE_DIR}/key" ]; then
    source ${INCLUDE_DIR}/key
    echo "Using saved key"
fi

if [ ! "$(docker images --format '{{.Repository}}:{{.Tag}}' | grep nerva/ledger)" ]; then
	docker pull nerva/ledger
fi

function clean()
{
    rm -f ${INCLUDE_DIR}/appinfo
    docker run --rm -i --privileged -v ${ROOT_DIR}:/code --user 1000:1000 --name nerva_ledger -t nerva/ledger:latest "make clean"
    exit 0
}

function make()
{
    docker run --rm -i --privileged -v ${ROOT_DIR}:/code --user 1000:1000 --name nerva_ledger -t nerva/ledger:latest "make"

    data_size="$(cat ${ROOT_DIR}/debug/app.map | grep _nvram_data_size | tr -s ' ' | cut -f2 -d ' ')"
    icon_hex="$(python3 -m tools.icon ${ROOT_DIR}/images/icon_nerva.gif hexbitmaponly)"

    echo "export APP_SIZE=${data_size}" > ${INCLUDE_DIR}/appinfo
    echo "export ICON_HEX=${icon_hex}" >> ${INCLUDE_DIR}/appinfo
    exit 0
}

$1

make