#!/bin/bash
source "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"/include/env

function install()
{
    if ! [ -d "${SCRIPT_DIR}/loader" ]; then
        virtualenv -p python3 loader
        source ${SCRIPT_DIR}/loader/bin/activate
        pip3 install pycryptodomex ECPy ledgerblue

        pkgdir=$(python3 -c "from distutils.sysconfig import get_python_lib; print(get_python_lib())")

        if [ ! -d "${pkgdir}" ]; then
            echo "Could not determine site-packages folder. seedconv utility will be unavailable"
        else
            cp -r ${ROOT_DIR}/tools/python/src/ledger/monero ${pkgdir}/tools
            cp ${ROOT_DIR}/external/sdk/icon.py ${pkgdir}/tools/icon.py
        fi

    else
        echo "Ledger virtualenv already created"
    fi

	exit 0
}

function uninstall()
{
    rm -rf "${SCRIPT_DIR}/loader"
	exit 0
}

$1

install
